Hero
ChaikaMe/profit-project pull request #9
Opened 2023-11-26 08:59 UTC by Anlika23

2023-11-26 14:47 UTC, Anlika23 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Hero](https://trello.com/c/8T5V5VjQ/2-hero)

2023-11-26 16:18 UTC, ChaikaMe requested changes
Потрібні виправлення:

1. Паддінг топ на секції треба 60 пікселів (хедер має сталу величину тож орієнтуватися воно буде від розірів хедера а не найбільшого елементу)
2. В мобільній версії при розмірі 320 елементи прилипають до країв, треба щоб падінг все також вжимав весь контент 
3. Вистав в base.css margin: 0; 
Щоб уникнути зайвих відступів (воно є в актуальній версії)
4. Стрілочка в кнопці має некоректний розмір
5. Білий колір для заголовку дублюється (він є в базових)
6. Контент прилипає на таблет версії (рекомендую просто підтягнути актуальну версію і вставити проект туди, там проблема з ієрархією стилів була пофікшена, це скорше всього рішить проблему з прилипанням)
В таблет версії падіг має бути 32
7. Текст кнопки міняється починаючи з таблетки
8. Розмір тексту заголовку має мінятися на 1440
9. Гумове вікно має бути тільки в проміжку з 320 до 375, все інше - адаптивне. В тебе воно гумове майже завжди
10. Зоображення також розтягується та стискається в залежності від екрану. Треба фіксити ситуацію з падінгами. Марджини по бокам треба прибрати.

Якщо це все виправити сторінка має бути як треба, проте я рекомендую тобі звірити все ще раз самостійно

2023-11-26 19:42 UTC, ChaikaMe requested changes
fix

2023-11-27 10:39 UTC, ChaikaMe approved these changes
Чудова робота!

Тіки що деякі стилі мені здається можна прибрати, але ми це робити не будемо))

2023-11-27 10:39 UTC, merged